name: XyMythicItemGui
version: '2.3'
main: org.xyplugin.xymythicitemgui.XyMythicItemGui
api-version: '1.12'
depend: [MythicMobs]
author: YourName

commands:
  xygui:
    description: XyMythicItemGui 主命令
    usage: /xygui [open|i|e|search|give|reload]
    aliases: [xmi]

permissions:
  xygui.use:
    description: 允许使用 GUI
    default: true
  xygui.admin:
    description: 允许使用和重载插件
    default: op
